<?php
$this->layout()->setVariables([
    'htmlHeadAppend' => $this->getReCaptchaScriptTag(),
    'htmlHeadTitle'  => 'Change Password',
]);
$errors = $this->flash()->get('errors');
?>
<div class="columns one-column">
    <div class="panel">
        <h1>Change Password</h1>

        <form action="/account/change-password" method="post">

        <p>
            Current Password<br>
            <input type="password" name="current-password">
        </p>

        <p>
            New Password<br>
            <input type="password" name="new-password">
        </p>

        <p>
            Confirm New Password<br>
            <input type="password" name="confirm-new-password">
        </p>

        <?= $this->getReCaptchaDivTag(); ?>

        <input type="hidden" name="https-token" value="<?= $this->escape($user->getHttpsToken()); ?>">

        <p><input type="submit" value="Change Password"></p>

        </form>

        <?php if ($errors): ?>
            <ul class="errors">
                <?php foreach ($errors as $error): ?>
                    <li><?= $this->escape($error); ?></li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
    </div>
</div>
