<?php
$this->layout()->setVariables([
    'htmlHeadTitle' => 'Reset Password',
    'useContainer'  => false,
]);
$this->getShowAdsService()->setShowAds(false);
?>
<div class="columns one-column">
    <div class="column">
        <div class="panel">
            <h1>Reset Password</h1>

            <form action="" method="post">
                <p>
                    New Password<br>
                    <input type="password" name="new_password">
                </p>

                <p>
                    Confirm New Password<br>
                    <input type="password" name="confirm_new_password">
                </p>

                <p><input type="submit" value="Submit"></p>
            </form>

            <?php if ($errors): ?>
                <ol class="errors">
                    <?php foreach ($errors as $error): ?>
                        <li><?= $this->escape($error); ?></li>
                    <?php endforeach ?>
                </ol>
            <?php endif ?>
        </div>
    </div>
</div>
