<?php
$this->layout()->setVariables([
    'htmlHeadTitle' => 'Successfully Changed Password',
    'useContainer'  => false,
]);
$this->getShowAdsService()->setShowAds(false);
?>
<div class="columns one-column">
    <div class="column">
        <div class="panel">
            <h1>Successfully Changed Password</h1>

            <p>You may now <a href="/login">login</a> with the new password.</p>
        </div>
    </div>
</div>
