<?php
if (empty($htmlHeadTitle)) {
    $htmlHeadTitle = 'monthly-basis/user';
}
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <title><?= $this->escape($htmlHeadTitle); ?></title>

        <?php if (isset($htmlHeadAppend)): ?>
            <?= $htmlHeadAppend ?>
        <?php endif ?>
    </head>
    <body>
        <header>
            header
        </header>
        <main>
            <?= $this->content ?>
        </main>
        <footer>
            footer
        </footer>
    </body>
</html>
